
delta.transactions.path=delta/transactions
checkpoint.path=checkpoint/transactions

# Kafka
kafka.bootstrap.servers=localhost:9092
kafka.topic.transactions=transactions
kafka.starting.offsets=earliest

# Spark
spark.master=local[*]

# S3 Bronze
s3.path.bronze=s3a://fraud-detection-pipeline-sagar/transactions/raw

# S3 Silver
s3.path.curated=s3a://fraud-detection-pipeline-sagar/transactions/curated
s3.path.orphaned=s3a://fraud-detection-pipeline-sagar/transactions/orphaned

# S3 Gold
s3.path.fraud.alerts=s3a://fraud-detection-pipeline-sagar/transactions/fraud_alerts

# S3 Checkpoints
s3.path.checkpoint=s3a://fraud-detection-pipeline-sagar/transactions/checkpoints
